# .fast-format-x.yaml
# One command to auto-format every changed file. All formatters run in parallel.
# Learn more at: https://ffx.bfoos.net
# Install with: curl -LsSf https://ffx.bfoos.net/install.sh | bash
# Run `ffx init` to install the pre-commit hook and scaffold this config.

version: 1

tools:
  # Web files: CSS, Markdown, JSON, YAML, HTML
  # Prettier: the standard for web file formatting
  - name: prettier
    include:
      - "**/*.css"
      - "**/*.md"
      - "**/*.json"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.html"
    exclude: ["node_modules/**", "dist/**", "build/**"]
    cmd: npx
    args: [prettier, --write]
    check_args: [prettier, --check]
